### ISSUE TITLE
Invalid MIB

### ISSUE THREAD

**Issue by fbacchella** [hs-cx/snmp_mib_archive#10]
The file https://github.com/hsnodgrass/snmp_mib_archive/blob/master/snmp_mib_archive/r/RFC1406-MIB.mib is really broken. Assignation token is `::=` not `=`.

**Comment by hsnodgrass** [comment]
Interesting, thanks for letting me know! I'll try and find a known-good MIB for RFC 1406 and compare / replace the one in this repo.
